### ISSUE TITLE
Add / adjust vars KeepAlived

### ISSUE THREAD

**Issue by kdp-cloud** [tfindley/Ansible-Collection-KeepAliveD#3]
Can you add a couple of extra vars for the KeepAlived playbooks (for example [here](https://github.com/tfindley/Ansible-Collection-KeepAliveD/blob/96dd9510400456a4ad0b53692b09b3818cbd3be3/playbooks/deploy_pass.yml#L13-L15))?

Especially the `keepalived_vxrrp_version` variable is quite important.

```yaml
keepalived_enabled:
keepalived_vip:
keepalived_vrid:
keepalived_state:
keepalived_priority:
keepalived_vxrrp_version:
```
